import React, { useState } from 'react';
import Modal from '../Modal';




function PhotoList({ category }) {
  const [isModalOpen, setIsModalOpen] = useState(false);
    const [currentPhoto, setCurrentPhoto] = useState();

      const [photos] = useState([
        {
          name: '1 Mortuous "Demo 2012"',
          category: 'releases',
          description: 'Release Date: 2012',
        },
        {
          name: '2 Caffa "Day of Disease"',
          category: 'releases',
          description: 'Release Date: 11-20-2013',
        }, 
       {
          name: '3 Cyanic "Litanies of Lust Unholy"',
          category: 'releases',
          description: 'Release Date: 1-11-2014',
        },
        {
          name: '4 Fiend "Demo 2013"',
          category: 'releases',
          description: 'Release Date: "1-11-2014"',
        },
        {
          name: '5 Xenotaph "Vitae Lactura"',
          category: 'releases',
          description: 'Release Date: 3-23-2014',
        },
        {
          name: '6 Swamp Witch "Gnosis"',
          category: 'releases',
          description: 'Release Date: 4-20-2014',
        },
        {
          name: '7 Badr Vogu "Agglomeration MMXIV"',
          category: 'releases',
          description: 'Release Date: 7-3-2014',
        },
        {
          name: '8 Naught "Tomhyggjublus"',
          category: 'releases',
          description: 'Release Date: 10-10-2014',
        },
        {
          name: '9 Cease "Humanity"',
          category: 'releases',
          description: 'Release Date: 12-12-2014',
        },
        {
          name: '10 Cloak "Succumb"',
          category: 'releases',
          description: 'Release Date: 3-11-2015',
        },
        {
          name: '11 Church - "Unanswered Hymns"',
          category: 'releases',
          description: 'Releaase Date: 4-12-2015',
        },
        {
          name: '12 Swamp Witch "The Slithering Bog"',
          category: 'releases',
          description: 'Release Date: 5-15-2015',
        },
        {
          name: '13 Swamp Witch "The Slithering Bog Chopped to Shit"',
          category: 'releases',
          description: 'Release Date: 4-12-2015',
        },
        {
          name: '14 Devoid "I & II"',
          category: 'releases',
          description: 'Release Date: 7-11-2015',
        }, 
        {
          name: '15 Beira "Vol.1"', 
          category: 'releases',
          description: 'Release Date: 7-11-2015',
        },
        
        {
          name: '16 Brume "Donkey"',
          category: 'releases',
          description: 'Release Date: 9-11-2015',
        },
        {
          name: '17 Hallucinator "Primeval Power"',
          category: 'releases',
          description: 'Release Date: 10-27-2015',
        },
        {
          name: '18 Defecrator "Tales of Defecration"',
          category: 'releases',
          description: 'Release Date: 11-11-2015',
        },
        {
          name: '19 Cease "Unfold"',
          category: 'releases',
          description: 'Release Date: 3-11-2016',
        },
        
        {
          name: '20 Rhizome S/T',
          category: 'releases',
          description: 'Release Date: 3-11-2016',
        },
        {
          name: ' 21 Modraniht "To the Dark Mothers',
        category: 'releases',
        description: 'Release Date: 6-26-2016',
        },
        {
          name: '22 Body Void "Ruins"',
        category: 'releases',
        description: 'Release Date: 6-26-2016',
        },
        {
          name: '23 Hands of Thieves "Feasting on Dark Intentions"',
        category: 'releases',
        description: 'Release Date: 9-11-2016',
        },
        
        {
          name: '24 Oozepus "Lypemania"',
        category: 'releases',
        description: 'Release Date: 12-12-2016',
        },
        {
          name: '25 Chronaexus "Outreach From a Withered Hand"',
        category: 'releases',
        description: 'Release Date: 12-12-2016',
        },
        {
          name: '26 Waning "Still Hours"',
        category: 'releases',
        description: 'Release Date: 2-17-2017',
        },
        {
          name: '27 Dismembered Carnage "Deranged Butchery"',
        category: 'releases',
        description: 'Release Date: 12-21-2016',
        },
        
        {
          name: '28 Caffa "Mental Enslavement"',
        category: 'releases',
        description: 'Release Date: 2-22-2017 ',
        },
        {
          name: '29 Rapid Decline "Less Power, More Violence"',
        category: 'releases',
        description: 'Release Date: 4-20-2017',
        },
        {
          name: '30 Daxma "The Nowhere of Shangri-La"',
        category: 'releases',
        description: 'Release Date: 4-20-2017',
        },
        {
          name: '31 Ensepulcher "No Sanctity in Death "',
        category: 'releases',
        description: 'Release Date: 4-20-2017',
        },
        {
          name: '32 Battle Hag "Tongue of the Earth"',
        category: 'releases',
        description: 'Release Date: 5-7-2017',
        },
         {
          name: '33 NOSTRUM "Infernal Tomb"',
        category: 'releases',
        description: 'Release Date: 6-6-2017',
        },
         {
          name: '34 Cosmic Reef Temple "Age of the Spaceborn"',
        category: 'releases',
        description: 'Release Date: 6-16-2017',
        },
         {
          name: '35 DWEL "Lodestone"',
        category: 'releases',
        description: 'Release Date: 6-26-2016',
        },
         {
          name: '36 Blazar "PHASE OMEGA"',
        category: 'releases',
        description: 'Release Date: 7-7-2017',
        },
         {
          name: '37 Owl Coven "Cosmic Void"',
        category: 'releases',
        description: 'Release Date: 7-27-2017',
        },
         {
          name: '38 Demonsmoke "Morphine Moonshine"',
        category: 'releases',
        description: 'Release Date: 8-1-2017',
        },
        {
          name: '39 Xenotaph "Media Morte in Vita Sumus"',
        category: 'releases',
        description: 'Release Date: 11-11-2017',
        },
         {
          name: '40 Mystic Priestess "S/T"',
        category: 'releases',
        description: 'Release Date: 12-22-2017',
        },
         {
          name: '41 Dipygus "Long Pig Feast"',
        category: 'releases',
        description: 'Release Date: 1-11-2018',
        },
         {
          name: '42 Vile Apparition "Atrocious Captivity"',
        category: 'releases',
        description: 'Release Date: 1-1-2018',
        },
         {
          name: '43 Dearth "Of Martyrdom and Polluted Faith"',
        category: 'releases',
        description: 'Release Date: 7-11-2018',
        },
         {
          name: '44 Atone "S/T"',
        category: 'releases',
        description: 'Release Date: 7-11-2018',
        },
        {
          name: '45 Occlith "Obscure Heresies"',
        category: 'releases',
        description: 'Release Date: 7-11-2018',
        },
         {
          name: '46 Gravecoven "Coughing Blood"',
        category: 'releases',
        description: 'Release Date: 7-11-2018',
        },
        {
          name: '47 Mortuous "Through Wilderness"',
        category: 'releases',
        description: 'Release Date: 6-22-2018',
        },
         { name: '48 Yarrow "Rebirth"',
        category: 'releases',
        description: 'Release Date: 9-11-2018',
        },
         { name: '49 Abyssal "Misanthrope"',
        category: 'releases',
        description: 'Release Date: 10-31-2018',
        },
         { name: '50 Evulse "Call of the Void"',
        category: 'releases',
        description: 'Release Date: 10-22-2018',
        },
         { name: '51 Swamp Witch "Dead Ritauls"',
        category: 'releases',
        description: 'Release Date: 5-10-2019',
        },
          {
          name: '52 Trapped Within Burning Machinery "The Putrid Stench of Decaying Self"',
        category: 'releases',
        description: 'Release Date: 7-4-2019',
        },
        { name: '53 Barren Altar "Entrenched in the Faults of the Earth"',
        category: 'releases',
        description: 'Release Date: 7-4-2019',
        },
        {  name: '54 Denunciation "Garbage Burial"',
        category: 'releases',
        description: 'Release Date: 8-11-2019',
        },
        {  name: '55 False Figure "A Promised End"',
        category: 'releases',
        description: 'Release Date: 9-29-2019',
        },
        {  name: '56 Shrinkwrap Killers "Parents + FBI = Cahoots"',
        category: 'releases',
        description: 'Release Date: 11-7-2019',
        },
          {
          name: '57 Exulansis "Sequestered Sympathy"',
        category: 'releases',
        description: 'Release Date: 7-7-2019',
        },
         { name: '58 Chrome Ghost "The Diving Bell"',
        category: 'releases',
        description: 'Release Date: 11-30-2019 ',
        },
        {  name: '59 Letharia "S/T"',
        category: 'releases',
        description: 'Release Date: 11-30-2019',
        },
        {  name: '60 Cyanic "S/T"',
        category: 'releases',
        description: 'Release Date: 4-12-2020',
        },
        {  name: '61 Pastoral "S/T"',
        category: 'releases',
        description: 'Release Date: 4-19-2020',
        },
        { name: '62 TZOMPANTLI "S/T"',
        category: 'releases',
        description: 'Release Date: 4-26-2020',
        },
       { name: '63 Occlith "Gates, Doorways, and Endings"',
        category: 'releases',
        description: 'Release Date: 5-1-2020',
        },
        { name: '64 Sectarian Bloom "S/T"',
        category: 'releases',
        description: 'Release Date: 6-6-2020',
        },
        /*{ name: '65 Wasteland Coven "Ruined"',
        category: 'releases',
        description: 'Release Date: 6-26-2020',
        },
        { name: '66 Torture Tomb "Killing to See How it Feels"',
        category: 'releases',
        description: 'Release Date: 6-6-2020',
        },
        { name: '67 Hellish Form "MMXX"',
        category: 'releases',
        description: 'Release Date: 7-17-2020',
        },
        { name: '68 Crushing the Scepter "Echoing Screams of Madness and Delusion"',
        category: 'releases',
        description: 'Release Date: 7-27-2020',
        },
        {  name: '69 Sky Pig "Hell is Inside You"',
        category: 'releases',
        description: 'Release Date: 7-27-2020',
        },
        { name: '70 Caged "Stricken by Continuance"',
        category: 'releases',
        description: 'Release Date: 8-7-2020',
        },
        { name: '71 Sepulchral Curse "A Birth in Death"',
        category: 'releases',
        description: 'Release Date: 8-7-2020',
        },
        { name: '72 Stagnater "The Guillotine Demo"',
        category: 'releases',
        description: 'Release Date: 8-7-2020',
        },
        { name: '73 Exhumation "Eleventh Formulae"',
        category: 'releases',
        description: 'Release Date: 8-7-2020',
        },
        { name: '74 Caffa "Compilation"',
        category: 'releases',
        description: 'Release Date: 9-4-2020',
        },
        { name: '75 Kombat "New Dimensions of Pain"',
        category: 'releases',
        description: 'Release Date: 9-4-2020',
        },
        { name: '76 Saturno "Menhir"',
        category: 'releases',
        description: 'Release Date: 9-4-2020',
        },
        { name: '77 Evulse "Pustulant Spawn"',
        category: 'releases',
        description: 'Release Date: 9-4-2020',
        },
        { name: '78 Cult Graves "Strange Cumtons"',
        category: 'releases',
        description: 'Release Date: 10-31-2020',
        },
        { name: '79 Alone "Useless Existence"',
        category: 'releases',
        description: 'Release Date: 10-31-2020',
        },
        { name: '80 Agonanist "The Cynicism of Solitude"',
        category: 'releases',
        description: 'Release Date: 10-31-2020',
        },
        { name: '81 Stygian Crown "S/T"',
        category: 'releases',
        description: 'Release Date: 10-31-2020',
        },
        { name: '82 Peace Killers "Magnetic Mountain"',
        category: 'releases',
        description: 'Release Date: 10-31-2020',
        },
        { name: '83 Bruja "Mundo Triste"',
        category: 'releases',
        description: 'Release Date: 12-12-2020',
        },
        { name: '84 Mordom "Eternal Solitude"',
        category: 'releases',
        description: 'Release Date: 12-12-2020',
        },
        { name: '85 Burning Palace "Hollow"',
        category: 'releases',
        description: 'Release Date: 12-12-2020',
        },
        { name: '86 Naughtskeid "Ultimate Infernal Nightscape"',
        category: 'releases',
        description: 'Release Date: 12-12-2020',
        },
        { name: '87 Empyreal "S/T"',
        category: 'releases',
        description: 'Release Date: 12-12-2020',
        },
        { name: '88 Intrinsic Maleficence "Relapse"',
        category: 'releases',
        description: 'Release Date: 12-12-2020',
        },
        { name: '89 Gravkvade "Graviruin"',
        category: 'releases',
        description: 'Release Date: 1-11-2021',
        },
        { name: '90 Carrion Bloom "Heretic Howl"',
        category: 'releases',
        description: 'Release Date: 1-11-2021',
        },
        { name: '91 Battle Hag "Celestial"',
        category: 'releases',
        description: 'Release Date: 1-11-2021 ',
        },
        {  name: '92 Graveolence "Anthropomancy"',
        category: 'releases',
        description: 'Release Date: 3-21-2021',
        },
        { name: '93 Rotten Funeral "S/T"',
        category: 'releases',
        description: 'Release Date: 3-21-21',
        },
        { name: '94 Hollow Mirrors "II"',
        category: 'releases',
        description: 'Release Date: 3-21-21',
        },
        { name: '95 Neyquam "Morbid Devourment"',
        category: 'releases',
        description: 'Release Date:  3-21-21',
        },
        { name: '96 Abyzou "Aeternum"',
        category: 'releases',
        description: 'Release Date: 3-21-21',
        },
        { name: '97 Fossilization "He Whose Name Was Long Forgotten"',
        category: 'releases',
        description: 'Release Date: 3-21-2021',
        },
        { name: '98 Civerous "Live Promo MMXXI"',
        category: 'releases',
        description: 'Release Date: 3-21-2021',
        },
        {  name: '99 Molten "Dystopian Syndrome"',
        category: 'releases',
        description: 'Release Date: 5-5-2021',
        },
        { name: '100 Kruelty "Promo 2021"',
        category: 'releases',
        description: 'Release Date: 4-2-2021',
        },
        { name: '101 Miserable Creature "2"',
        category: 'releases',
        description: 'Release Date: 5-5-2021',
        },
        { name: '102 Kombat/Torture Tomb SPLIT "Greased Then Released"',
        category: 'releases',
        description: 'Release Date: 4-20-2021',
        },
        { name: '103 Kosmodemonic "Liminal Light"',
        category: 'releases',
        description: 'Release Date: 5-7-2021',
        },
        { name: '104 Shroud of Vulture "Upon a Throne of Jackals"',
        category: 'releases',
        description: 'Release Date: 6-6-2021',
        },
        ////////////////////////
        
        {  name: '105 Exhumation "Opus Death"',
        category: 'releases',
        description: 'Release Date: 6-6-2021',
        },
        { name: '106 Funerealm "S/T"',
        category: 'releases',
        description: 'Release Date: 6-6-2021',
        },
        { name: '107 Tentacult "Obsidian Blade"',
        category: 'releases',
        description: 'Release Date: 6-6-2021',
        },
        { name: '108 Low Flesh "S/T"',
        category: 'releases',
        description: 'Release Date: 6-6-2021',
        },
        { name: '109 Funerelic "Demo '21"',
        category: 'releases',
        description: 'Release Date: 6-6-2021',
        },
        { name: '110 Mortuary Punishment "Brotherhood and Genocide"',
        category: 'releases',
        description: 'Release Date: 6-6-2021',
        },
        { name: '111 Anharat "Blood Sorcery"',
        category: 'releases',
        description: 'Release Date: 6-6-2021',
        },
        { name: '112 Mosara "S/T"',
        category: 'releases',
        description: 'Release Date: 5-28-2021',
        },
        { name: '113 Shitbag "Burden"',
        category: 'releases',
        description: 'Release Date: 7-27-2021',
        },
        { name: '114 Ancient Tome "Final Tomb"',
        category: 'releases',
        description: 'Release Date: 7-27-2021',
        },
        { name: '115 Cessation "S/T"',
        category: 'releases',
        description: 'Release Date: 7-27-2021',
        },
        //////////
        { name: '116 Wasteland Coven "Nothin is Real - Turmoil"',
        category: 'releases',
        description: 'Release Date: 8-6-2021',
        },
        { name: '117 Ghorot "Loss of Light"',
        category: 'releases',
        description: 'Release Date: 9-3-2021',
        },
        { name: '118 Mortuary Punishment "Pride.Power.Punishment"',
        category: 'releases',
        description: 'Release Date: 9-3-2021',
        },
        { name: '119 Chrome Ghost "Double EP"',
        category: 'releases',
        description: 'Release Date: 11-5-2021',
        },
        { name: '120 Chrome Ghost "Choir of the Low Spirits"',
        category: 'releases',
        description: 'Release Date: 11-5-2021',
        },
        { name: '121 Harlequin "Deep Throat"',
        category: 'releases',
        description: 'Release Date: 11-21-2021',
        },
        { name: '122 Religious Observance "S/T"',
        category: 'releases',
        description: 'Release Date: 11-22-2021',
        },
        { name: '123 Sleipnir "Ambient Tape 04"',
        category: 'releases',
        description: 'Release Date: 11-26-2021',
        },
        { name: '124 Telluric Effluvium "Dissolution of the Threefold Self"',
        category: 'releases',
        description: 'Release Date: 12-3-2021',
        },
        { name: '125 Slog "S/T"',
        category: 'releases',
        description: 'Release Date: 12-3-2021',
        },
        { name: '126 Puke Mutant "An Unsightly Desecration"',
        category: 'releases',
        description: 'Release Date: 12-3-2021',
        },
        { name: '127 Iron Front "Flayed Alive"',
        category: 'releases',
        description: 'Release Date: 11-5-2021',
        },
        { name: '128 Mutate "Mutated Deformation"',
        category: 'releases',
        description: 'Release Date: 12-3-2021',
        },
        { name: '129 Civerous "Decrepit Flesh Relic"',
        category: 'releases',
        description: 'Release Date: 11-19-2021',
        },
        { name: '130 Mordom "Cry of the Dying World"',
        category: 'releases',
        description: 'Release Date: 12-10-2021',
        },
        { name: '131 Aequorea "DIM"',
        category: 'releases',
        description: 'Release Date: 1-7-2022',
        },
        { name: '132 Pendulous "A Palpable Sense of Love & Loss"',
        category: 'releases',
        description: 'Release Date: 2-4-2022',
        },
        { name: '133 Class Traitor "Calving"',
        category: 'releases',
        description: 'Release Date: 2-4-2022',
        },
        { name: '134 Ceremonial Decay "The Crescent and the Cross"',
        category: 'releases',
        description: 'Release Date: 2-11-2022',
        },
        { name: '135 Civerous/Stygian Obsession "Anniversary of Affliction"',
        category: 'releases',
        description: 'Release Date: 2-11-2022',
        },
        { name: '136 An Evening Redness "S/T"',
        category: 'releases',
        description: 'Release Date: 2-25-2022',
        },
        { name: '137 Telluric Effluvium "Voyage of Sentient Decay"',
        category: 'releases',
        description: 'Release Date: 3-4-2022',
        },
        { name: '138 Fellbeast "S/T"',
        category: 'releases',
        description: 'Release Date: 3-4-2022',
        },
        { name: '139 Veruta "Criterion Void"',
        category: 'releases',
        description: 'Release Date: 3-4-2022',
        },
        { name: '140 Malignant "Reign of Decrepitude"',
        category: 'releases',
        description: 'Release Date: 3-4-2022',
        },
        {  name: '141 Teratoma "Purulent Manifestations"',
        category: 'releases',
        description: 'Release Date: 3-4-2022',
        },
        {  name: '142 GRAV|ANDE "GRAVKVADE"',
        category: 'releases',
        description: 'Release Date: 4-1-2022',
        },
        {  name: '143 REPUTDEATH "Dissecting Goryfication"',
        category: 'releases',
        description: 'Release Date: 4-1-2022',
        },
        {  name: '144 Shrouded Infinity "Through Caverns Unknown"',
        category: 'releases',
        description: 'Release Date: 4-1-2022',
        },
        {  name: '145 Sepulchral Curse "Deathbed Sessions"',
        category: 'releases',
        description: 'Release Date: 5-6-2022',
        },
         { name: '146 Carrion Bloom "Sacraments of Pestilence"',
        category: 'releases',
        description: 'Release Date: 5-6-2022',
        },
        {  name: '147 Vomit Rot "Rotten Vomit"',
        category: 'releases',
        description: 'Release Date: 6-3-2022 ',
        },
        {  name: '148 Sulfuric Hated "Demo MMXXII"',
        category: 'releases',
        description: 'Release Date: 6-3-2022',
        },
        {  name: ' 149 Livssyke "Solace in Worms"',
        category: 'releases',
        description: 'Release Date: 6-3-2022',
        },
        {  name: '150 Dessication "Cold Dead Earth"',
        category: 'releases',
        description: 'Release Date: 6-13-2022',
        },
        {  name: '151 DVVELL "Quiescent"',
        category: 'releases',
        description: 'Release Date: 7-8-2022',
        },
        {  name: '152 Vorlust "Lick the Flesh"',
        category: 'releases',
        description: 'Release Date: 7-15-2022',
        },
         { name: ' "153 Sectarian Bloom "New Spring',
        category: 'releases',
        description: 'Release Date: 8-4-2022 ',
        },
         { name: ' "154 Abyssal - A Deep Sea Funeral"',
        category: 'releases',
        description: 'Release Date: 8-12-2022',
        },
         { name: ' "155 False Figure - Castigations"',
        category: 'releases',
        description: 'Release Date: 11-1-2022',
        },
         { name: ' "156 Renewer - Fading"',
        category: 'releases',
        description: 'Release Date: 12-12-2022',
        },
         { name: ' "157 POXX - Undying"',
        category: 'releases',
        description: 'Release Date: 12-12-2022',
        },
         { name: ' "158 Pastoral - II"',
        category: 'releases',
        description: 'Release Date: 12-12-2022',
        },
         { name: ' "159 Praying - True Hellman"',
        category: 'releases',
        description: 'Release Date: 1-13-2023',
        },
         { name: ' "160 Tentacult - Lacerating Pattern"',
        category: 'releases',
        description: 'Release Date: 2-3-2023',
        },
         { name: ' "161 Villainous Temple - Fill Creation Abuse"',
        category: 'releases',
        description: 'Release Date: 2-10-2023',
        },
         { name: ' "162 Menstrual Vampires - S/T"',
        category: 'releases',
        description: 'Release Date: 2-14-2023',
        },
        { name: ' "163 Bone Weapon - Thrive or Starve"',
        category: 'releases',
        description: 'Release Date: 2-24-2023',
        },
         { name: ' "164 Praying - Love Made Me A Coward"',
        category: 'releases',
        description: 'Release Date: 3-15-2023',
        },
         { name: ' "165 Aulnes - Resilience"',
        category: 'releases',
        description: 'Release Date: 3-15-2023',
        },
         { name: ' "166 Depleted - Failing"',
        category: 'releases',
        description: 'Release Date: 3-24-2023',
        },
         { name: ' "167 Ectospire - Formless Horrors"',
        category: 'releases',
        description: 'Release Date: 3-25-2023',
        },
         { name: ' "168 Sleipnir - V: Vengeful"',
        category: 'releases',
        description: 'Release Date: 4-7-2023',
        },
         { name: ' "169 Deep Cavity - Cathedral of Tears"',
        category: 'releases',
        description: 'Release Date: 4-7-2023',
        },
         { name: ' "170 Class Traitor - Broken Energy Highway"',
        category: 'releases',
        description: 'Release Date: 4-9-2023',
        },
         { name: ' "171 Deathgrave - It's Only Midnight"',
        category: 'releases',
        description: 'Release Date: ',
        },
         { name: ' "180"',
        category: 'releases',
        description: 'Release Date: ',
        },
         { name: ' "181"',
        category: 'releases',
        description: 'Release Date: ',
        },
         { name: ' "182"',
        category: 'releases',
        description: 'Release Date: ',
        },
         { name: ' "183"',
        category: 'releases',
        description: 'Release Date: ',
        },
         { name: ' "184"',
        category: 'releases',
        description: 'Release Date: ',
        },
         { name: ' "185"',
        category: 'releases',
        description: 'Release Date: ',
        },
         { name: ' "186"',
        category: 'releases',
        description: 'Release Date: ',
        },
         { name: ' "187"',
        category: 'releases',
        description: 'Release Date: ',
        },
         { name: ' "188"',
        category: 'releases',
        description: 'Release Date: ',
        },
         { name: ' "189"',
        category: 'releases',
        description: 'Release Date: ',
        },
         { name: ' "190"',
        category: 'releases',
        description: 'Release Date: ',
        }, { name: ' ""',
        category: 'releases',
        description: 'Release Date: ',
        },
         { name: ' ""',
        category: 'releases',
        description: 'Release Date: ',
        },
         { name: ' ""',
        category: 'releases',
        description: 'Release Date: ',
        },
         { name: ' ""',
        category: 'releases',
        description: 'Release Date: ',
        }, { name: ' ""',
        category: 'releases',
        description: 'Release Date: ',
        },
         { name: ' ""',
        category: 'releases',
        description: 'Release Date: ',
        },
         { name: ' ""',
        category: 'releases',
        description: 'Release Date: ',
        },
         { name: ' ""',
        category: 'releases',
        description: 'Release Date: ',
        },
         { name: ' ""',
        category: 'releases',
        description: 'Release Date: ',
        },
         { name: ' ""',
        category: 'releases',
        description: 'Release Date: ',
        },
         { name: ' ""',
        category: 'releases',
        description: 'Release Date: ',
        }, { name: ' ""',
        category: 'releases',
        description: 'Release Date: ',
        },
         { name: ' ""',
        category: 'releases',
        description: 'Release Date: ',
        },
         { name: ' ""',
        category: 'releases',
        description: 'Release Date: ',
        },
         { name: ' ""',
        category: 'releases',
        description: 'Release Date: ',
        },
        { name: ' ""',
        category: 'releases',
        description: 'Release Date: ',
        },
         { name: ' ""',
        category: 'releases',
        description: 'Release Date: ',
        },
         { name: ' ""',
        category: 'releases',
        description: 'Release Date: ',
        }, { name: ' ""',
        category: 'releases',
        description: 'Release Date: ',
        },
         { name: ' ""',
        category: 'releases',
        description: 'Release Date: ',
        },
         { name: ' ""',
        category: 'releases',
        description: 'Release Date: ',
        },
         { name: ' ""',
        category: 'releases',
        description: 'Release Date: ',
        },
        { name: ' ""',
        category: 'releases',
        description: 'Release Date: ',
        },
         { name: ' ""',
        category: 'releases',
        description: 'Release Date: ',
        },
         { name: ' ""',
        category: 'releases',
        description: 'Release Date: ',
        }, { name: ' ""',
        category: 'releases',
        description: 'Release Date: ',
        },
         { name: ' ""',
        category: 'releases',
        description: 'Release Date: ',
        },
         { name: ' ""',
        category: 'releases',
        description: 'Release Date: ',
        },
         { name: ' ""',
        category: 'releases',
        description: 'Release Date: ',
        },


        */
        
      ]);
      
      const currentPhotos = photos.filter((photo) => photo.category === category);

      const toggleModal = (image, i) => {
        setCurrentPhoto({...image, index: i});
        setIsModalOpen(!isModalOpen);
        
      }
      
    return (
      <div>
        {isModalOpen && (
       <Modal currentPhoto={currentPhoto} onClose={toggleModal} />
        )}       
          <div className="flex-row">
            {currentPhotos.map((image, i) => ( 
            <img
            src={require(`../../assets/small/${category}/${i}.jpg`)}
            alt={image.name}
            className="img-thumbnail mx-1"
            onClick={() => toggleModal(image, i)}
            key={image.name}
           />
           ))}
           <p>
          title
        </p>
        </div>
        
      </div>
    );
  };

  export default PhotoList;

